language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t adityapandey97/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true adityapandey97/docker-react npm run test -- --coverage